Repository owncloud/docs-main, pull requests merged in 2024-01, with the labels that each got.

#2 Restore original ocis release notes
  modules/ROOT/pages/ocis_release_notes.adoc
Labels: deployment

#4 Fix CI and add redirects
  .drone.star
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/how_to_contribute.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/ocis_release_notes.adoc
  modules/ROOT/pages/ocis_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/ROOT/pages/server_releases.adoc
Labels: deployment

#6 fix: correct the link reference in README
  README.md
Labels: documentation

#7 Create dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#13 Antora 3.1 upgrade
  .drone.star
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  bin/ownCloudDocPdf.py
  docs/new-version-branch.md
  es-docker-compose.yml
  ext-antora/generate-index.js
  ext-asciidoc/remote-include-processor.js
  ext-asciidoc/tabs.js
  generator/generate-site.js
  generator/xref-validator.js
  package.json
  site.yml
  yarn.lock
Labels: deployment, dependencies

#16 Just a small internal link fix
  docs/new-version-branch.md
Labels: documentation
